config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#one'

  get '/pages/one', to: 'pages#one'
  get '/pages/two', to: 'pages#two'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end

  def four
  end

  def five
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_sidebar.html.erb
<div id="sidebar">
  <h4>SIDEBAR</h4>
  <div id="number_of_clicks">Try clicking the header</div>
  <input type="text" id="search_term" />
  <input type="button" id="search" value="Search" />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barista Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">

<div class="container">

  <div class="row">
    <div class="col-md-12">
      <div id="header">
        <h4>HEADER</h4>
        <p id="clickable">Try clicking here...</p>
      </div>
    </div>
  </div>

  <%= yield %>
</div>

</body>
</html>

app/views/pages/one.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Page One</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render 'sidebar' %>
  </div>

  <div class="col-md-8">
    <div id="main_one">
      <h4>MAIN ONE</h4>
      <p>This area will listen to the search event triggered from the sidebar..</p>

      <p id="search_results"></p>

      <p><%= link_to 'Page Two', pages_two_path %></p>
    </div>
  </div>
</div>

app/views/pages/two.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Page One</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render 'sidebar' %>
  </div>

  <div class="col-md-8">
    <div id="main_two">
      <h4>MAIN TWO</h4>

      <p><%= link_to 'Page One', pages_one_path %></p>
    </div>
  </div>
</div>